# start of Meshtastic configure yaml
channel_url: https://meshtastic.org/e/#CgcSAQE6AggNEhQIARAFOANAB0gBUBVoAcAGAcgGAQ
config:
  bluetooth:
    enabled: false
    fixedPin: 123456
    mode: FIXED_PIN
  device:
    disableTripleClick: true
    ledHeartbeatDisabled: true
    nodeInfoBroadcastSecs: 10800
  display:
    screenOnSecs: 600
  lora:
    configOkToMqtt: true
    hopLimit: 7
    ignoreMqtt: true
    modemPreset: SHORT_SLOW
    region: EU_868
    sx126xRxBoostedGain: true
    txEnabled: true
    txPower: 21
    usePreset: true
  network:
    ntpServer: meshtastic.pool.ntp.org
  position:
    broadcastSmartMinimumDistance: 100
    broadcastSmartMinimumIntervalSecs: 30
    fixedPosition: true
    gpsMode: NOT_PRESENT
    gpsUpdateInterval: 10800
    positionBroadcastSecs: 10800
    positionBroadcastSmartEnabled: false
    positionFlags: 811
  power:
    deviceBatteryInaAddress: 65
    isPowerSaving: true
    lsSecs: 300
    minWakeSecs: 10
    sdsSecs: 4294967295
    waitBluetoothSecs: 60
  security:
    adminKey:
    - 'base64:'
    - 'base64:'
    - 'base64:'
    privateKey: base64:QAz6yDMVInhzuQiQDh7jY7LLFPN6vxbb7/3Kd7kON2E=
    publicKey: base64:o+xiZ+IDh+n1sLstom8afXcsBWvE/5SpxaAC6kj5UyI=
    serialEnabled: true
location:
  alt: 90
  lat: 51.0918656
  lon: 6.2128128
module_config:
  ambientLighting:
    blue: 18
    current: 10
    green: 201
    red: 176
  detectionSensor:
    detectionTriggerType: LOGIC_HIGH
    minimumBroadcastSecs: 45
  mqtt:
    address: mqtt.meshtastic.org
    encryptionEnabled: true
    password: large4cats
    root: msh/EU_868
    username: meshdev
  telemetry:
    deviceUpdateInterval: 3600
    environmentMeasurementEnabled: true
    environmentUpdateInterval: 3600
    powerMeasurementEnabled: true
    powerUpdateInterval: 3600
owner: Meshtastic SolarNode
owner_short: '0000'

